apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sp-dx-sde
  description: DevEX (Service Platform) SDE team
spec:
  type: team
  profile:
    displayName: the SDE team
  children: []
  members: [guest]
